config/routes.rb
Schema::Application.routes.draw do
	match "login" => "shoppers#login", :as => :login
	match "out" => "shoppers#logout", :as => :out
	match "m" => "products#choose#categpage", :as => :m
	
  resources :retailers do
  	member do
  		get 'orders'
  	end
  	collection do
  		get 'delivery_times'
      post 'order_sent'
      post 'order_delivered'
      post 'undo_order_delivery'
  	end
  end

  resources :shoppers do
		member do
			get 'orders'
			get 'copy'
			post 'login_check_ajax'
			
		end
		collection do
				post 'register'
				get 'mobile_register'
				get 'mobile_verify'
				get 'mobile_remind_password'
				get 'getorders'
				get 'login'
				post 'login_check'
				post 'login_check_ajax'
				get 'logout'
    end
	end
  resources :items do
		collection do
				get 'select'
				get 'remove'
				get 'checkcart'
				get 'favorites'
        end
	end
  resources :shoppingcarts do
		collection do
				get 'checkout'
				get 'placeorder'
				get 'getorders'
				post 'processOrder'
				get 'get_cart_details'
    end
	end

  resources :brands

  resources :subcategs

  resources :categs 

  resources :products do
  collection do
				get 'choose'			
        end
	end
	
	resources :admin do
	collection do
		get 'compute_subcategbrand_promotions'
		get 'autocompute_product_promotions'
	end
	end
	
	resources :my_lists do
  collection do
				get 'create_my_list'
				get 'all_my_lists'
				get 'get_by_id'
        end
	end

end

app/models/shopper.rb
require 'simple_record'
class Shopper < SimpleRecord::Base
  
	set_domain_name :shopper
	
  has_strings			"name",   
									"mobile",
									"email",
									"address", 
									"userid",   
									"password", 
									"location",  
									"role", 
									"status", 
									"auth_token", 
									"auth_token_timestamp"
		
	has_ints				"auth_token_retry_count"
	
	def is_retailer
			role.include?("retailer")
	end
	
	def is_admin
			role.include?("admin")
	end
	
	has_strings :retailer_id
#	belongs_to :Retailer

	# if user id matches pattern of 10 digits its a mobile number
	def is_userid_mobile
		return !((self.userid =~ /\A\d{10}\z/).nil?)
	end

end

app/controllers/shoppers_controller.rb
class ShoppersController < ApplicationController
	
	include SmsMsg
	
	MAX_AUTH_RETRIES = 3	
	
  layout "choose_onepg"
  # GET /shoppers
  # GET /shoppers.json
  def index
    @shoppers = Shopper.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json =>  @shoppers }
    end
  end

  # GET /shoppers/1
  # GET /shoppers/1.json
  def show
    @shopper = Shopper.find_by_id(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json =>  @shopper }
    end
  end

  # GET /shoppers/new
  # GET /shoppers/new.json
  def new
    @shopper = Shopper.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json =>  @shopper }
    end
  end

  # GET /shoppers/1/edit
  def edit
    @shopper = Shopper.find_by_id(params[:id])
		
		if (@shopper.nil?)
			redirect_to "/shoppers/login",:alert => "Your current session has expired. Please log out and login again."
			return
		end
  end
	
	def copy
    @shopper_orig = Shopper.find_by_id(params[:id])	
		logger.debug("Shopper orig: #{@shopper_orig}")
		if (@shopper_orig.nil?)
				redirect_to "/shoppers/login",:alert => "Your current session has expired. Please log out and login again."
				return
			end
			
		#@shopper = Shopper.new(params[:id])
		#logger.debug("mew id #{@shopper.id}")
		@shopper = @shopper_orig.dup
		@shopper.id = nil
		
  end

  # POST /shoppers
  # POST /shoppers.json
  def create
		
		logger.debug "creating new shopper: #{params[:shopper]}"
    
		@result = { :status => 'created', :message => 'shopper was created' }
		
		@shopper = Shopper.new(params[:shopper])

		@oldshopper = Shopper.find(:first, :conditions => ["userid = ? ",@shopper.userid ])
		
		if @oldshopper == nil
			
			if (@shopper.is_userid_mobile)
				@result = { :status => 'error', :message => "Shopper with specified userid #{@shopper.userid} has to be verified first" }
				render :json => @result 
				return
			end
			
			logger.debug ("shopper does not exist, creating new")
			@shopper.save
			respond_to do |format|
				format.html { redirect_to "/shoppers", :notice =>  'Shopper was successfully created.' }
				format.json { render :json =>  @result } #@shopper, :status => :created, :location=> @shopper }
			end
		else
			
			if (@oldshopper.is_userid_mobile)
				
				if (@oldshopper.status == 'verified')
					
					@oldshopper.name = @shopper.name   
					@oldshopper.mobile = @shopper.mobile
					@oldshopper.email = @shopper.email
					@oldshopper.address = @shopper.address
					@oldshopper.userid = @shopper.userid
					@oldshopper.password = @shopper.password
					@oldshopper.location = @shopper.location
					@oldshopper.role = @shopper.role
					
					
					@default_retailer = Retailer.find_by_name('Test Bazaar')
					if (!@default_retailer.nil?)
						@oldshopper.retailer_id = @default_retailer.id
					end
					@oldshopper.status = 'ready'
					
					@oldshopper.save
					
					@result = { :status => 'created', :message => 'Shopper was created' }
					
				else
					
					@result = { :status => 'error', :message => "Shopper with specified userid #{@shopper.userid} should have status 'verified' and not #{@oldshopper.status}" }
					
				end
				
				render :json => @result 
				return

			end

			# the usual flow for alphanumeric ids
			logger.debug ("shopper already exists - not creating")
			@result[:status] = 'error'
			@result[:message] = "Shopper with specified userid #{@shopper.userid} already exists"
			
		  respond_to do |format|
				format.html { redirect_to "/shoppers/new", :notice =>  'Shopper was not created.' }
				format.json { render :json => @result } # @shopper.errors, :status => :unprocessable_entity }
		  end
		end
  end

  # PUT /shoppers/1
  # PUT /shoppers/1.json
  def update
    @shopper = Shopper.find_by_id(params[:id])
		
		if (@shopper.nil?)
			redirect_to "/shoppers/login",:alert => "Your current session has expired. Please log out and login again."
			return
		end

    respond_to do |format|
      if @shopper.update_attributes(params[:shopper])
        format.html { redirect_to @shopper, :notice =>  'Shopper was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action =>  "edit" }
        format.json { render :json =>  @shopper.errors, :status => :unprocessable_entity }
      end
    end
  end
	
# just a one time operation to update all date formats for delivery time
# probably will never be used again
	def archive_update_alldates
		#delivery_time
		
		logger.debug ("getting orders... #{session[:id]} -- #{session["cart_id"]}")
		@retailer_id = Shopper.find_by_id(session[:id]).retailer_id
		
		@shoppingcarts = Shoppingcart.find(:all, :conditions => ["delivery_time is not null"])
		
		@shoppingcarts.each_with_index do |cart, i|
			
			begin
				@del_date = DateTime.parse(cart.delivery_time) #.in_time_zone('Kolkata')
			rescue
				logger.debug "changing date to now"
				@del_date = DateTime.now #.in_time_zone('Kolkata')
			end
			
			cart.delivery_time = "#{@del_date}"
			cart.save
			
			logger.debug "#{cart.short_id} -- date: #{cart.delivery_time} ---- parsed as: #{@del_date}"
		end
			
	end
	
  def getorders
		
		@current_shoppingcart = Shoppingcart.find_by_id(params[:cart_id])
		@shoppingcarts = Shoppingcart.find(:all,
			:order => "updated desc",
			:conditions => ["(state is not null OR state != ?) AND shopper_id = ?", "", @current_shoppingcart.shopper_id]);
		
		puts ActiveSupport::JSON.encode(@shoppingcarts)
		
		render :json => @shoppingcarts;
		
  end

  # DELETE /shoppers/1
  # DELETE /shoppers/1.json
  def destroy
    @shopper = Shopper.find_by_id(params[:id])
		if (@shopper.nil?)
			format.html { redirect_to "/shoppers/login" }
			format.json { head :no_content }
			return
		end
    @shopper.destroy

    respond_to do |format|
      format.html { redirect_to shoppers_url }
      format.json { head :no_content }
    end
  end
	
	def get_shopper_login_url (shopper)
		if (shopper.is_admin) 
			logger.debug "Redirecting to admin - all retailers page"
			return "/retailers"
			#		render "/products/choose"
		elsif (shopper.is_retailer)
			logger.debug "Redirecting to retailer page"
			return "/retailers/#{@shopper.retailer_id}/orders"
			#		render "/products/choose"
		else
			logger.debug "Redirecting to products page"
			return "/products/choose#categpage"
			#		render "/products/choose"
		end
	end
 
	# Status returned can be one of:
	# ok - user logged in
	# ok_loggedin - user already logged in
	# err_password - password mismatch
	# err_userid_none: User id does not exist
	# err_userid_block: User id has been blocked due to too many retries and must register again
  def login_check
		
		# result to be returned as the ajax response in json
		@result =  { :status => 'ok', :message => 'Login succeeded', :url => '' }
		
		@userid = params[:userid]
		logger.debug "Login Check for userid: #{@userid}"
		
		# if user is empty, check if user is already logged in, 
		# and a valid session id exists
		if (params[:userid].blank?)
			@shopperid = session[:id]
			
			if(!session[:id].blank?)
				logger.debug "Session id is #{@shopperid}"
				@shopper = Shopper.find_by_id(@shopperid)
				
				if (@shopper.nil?)
					logger.debug "No shopper by that id"
					@result[:status] = 'err_notloggedin'
					@result[:message] = "No user already logged in, must sign in"
					@result[:url] = "/shoppers/login"
					render :json => @result
					return
				else
					logger.debug "Shopper logged in"
					@result[:status] = 'ok_loggedin'
					@result[:message] = "User already logged in as #{@shopper.userid}"
					@result[:url] = get_shopper_login_url (@shopper)
					logger.debug "Shopper URL: #{@result[:url]}"
					render :json => @result
					return
				end
			else
				logger.debug "Shopper not logged in"
				@result[:status] = 'err_notloggedin'
				@result[:message] = "No user already logged in, must sign in"
				@result[:url] = "/shoppers/login"
				render :json => @result
				return
			end
		else	# user id not empty, check credentials

			@userid = params[:userid].strip
			logger.debug "Login Check for user id #{@userid}"
		
			if (params[:password].empty?)
				logger.debug "Password empty"
				@result[:status] = 'err_password'
				@result[:message] = "Invalid password"
				@result[:url] = "/shoppers/login"
				render :json => @result
				return
			end
			
			@shopper = Shopper.find_by_userid(@userid)
		
			if (@shopper.nil?)
					@result[:status] = 'err_userid_none:'
					@result[:message] = "Userid does not exist"
					@result[:url] = "/shoppers/login"
					render :json => @result
					return
			else
				
				# if user id is a mobile number
				if (@shopper.is_userid_mobile)
					logger.debug "Login Check for mobilenumber, checking ready state"
					if (@shopper.status != 'ready')
						@result[:status] = 'err_usernotready'
						@result[:message] = "User has not completed mobile verification"
						@result[:url] = "/shoppers/login"
						logger.debug "Login Check for mobilenumber, failed, user not in ready state, redirecting to login"
						render :json => @result
						return
						# "Your mobile number needs to be registered and verified first."
					end

					logger.debug "Login Check for mobilenumber OK"
				end
				
				if (@shopper.password != params[:password])
					logger.debug "Password mismatch"
					
					@result[:status] = 'err_password'
					@result[:message] = "Invalid password"
					@result[:url] = "/shoppers/login"
					render :json => @result
					return
				else
					logger.debug "Password matched"
				end
			end
		end

		logger.debug("Has passed through all the checks so far")
		session["id"] = @shopper.id
		session[:user_role] = @shopper.role
		
		#@cart = Shoppingcart.find(:first, :conditions => ["shopper_id = ? and state = 'not_checked'",@shopper.id,@shopper.state])
		@cart = Shoppingcart.find(:first, :conditions => ["shopper_id = ? AND state is null",@shopper.id])
		if(!@cart.nil?)

app/helpers/shoppers_helper.rb
module ShoppersHelper
	def copy_shopper_path(shopper)
		"/shoppers/#{shopper.id}/copy"
  end
end

app/views/shoppers/_form.html.erb
<%= form_for(@shopper) do |f| %>
  <% if @shopper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shopper.errors.count, "error") %> prohibited this shopper from being saved:</h2>
      <ul>
      <% @shopper.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br />
    <%= f.text_field :mobile %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :userid %><br />
    <%= f.text_field :userid %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :role %><br />
    <%= select("shopper", "role", { "shopper - can only place orders" => "shopper", "retailer - can only view/process orders" => "retailer", "retailer & shopper - retailer who can also shop (testing)" => "shopper,retailer",  "admin - can only create shoppers/retailers" => "admin" } ) %>
	<!-- , "shopper retailer & admin" => "shopper,retailer,admin", -->
  </div>
  <div class="field">
    <br />
	<%= f.label :retailer %><br />
    <%= select("shopper", "retailer_id", Retailer.all.collect {|p| [ p.name, p.id ] }, {:include_blank => 'None'}) %>
  </div>
  <div class="field">
	<br /><br /><hr/>
  </div>
  <div class="actions">
    <%= f.submit "Register" %>
  </div>
<% end %>

app/views/shoppers/_loginform.html.erb


<div data-role="page" id="register_page" onmouseover="redirectToHome()">
	<div class="main_logo"><img src="/images/jiffeez_logo_25.png" /></div>
	
<a href="#" data-role="button" data-inline="true" data-theme="b" id="login_button_link">Sign in</a>
<a href="#" data-role="button" data-inline="true" data-theme="b" id="register_button_link">Register</a>
</div>	



<script>
  	
	if(localStorage.jiffeez_user_status == 'Login')
	{
		document.getElementById("login_button_link").style.display = "none";
		document.getElementById("register_button_link").style.display = "none";
	}
	else
	{
		document.getElementById("login_button_link").style.display = "block";
		document.getElementById("register_button_link").style.display = "block";
	}
	
	function redirectToHome()
	{
		if(localStorage.jiffeez_user_status == 'Login')
		{
			window.location.href = ("http://" + window.location.hostname + '/products/choose');	
		}
	}
	
</script>

app/views/shoppers/_loginform.html12.erb
<%= form_tag("/shoppers/login_check" , :method => "post") %>

<div>User ID: <%= text_field_tag 'userid' %></div>
<div>Password: <%= password_field_tag 'password' %></div>
<%= submit_tag "Login" %>
</form>

app/views/shoppers/copy.html.erb
<h1>Copy shopper</h1>

<%= render 'form' %>

<%= link_to 'Go Back', login_shoppers_path %>

app/views/shoppers/edit.html.erb
<h1>Editing shopper</h1>

<%= render 'form' %>

<%= link_to 'Show', @shopper %> |
<%= link_to 'Back', shoppers_path %>

app/views/shoppers/index.html.erb
<h1>Listing shoppers</h1>

<style>
  table
  {
	border-collapse:collapse;
  }
  table, th, td
  {
	border: 1px dotted gainsboro;
  }
</style>
<table>
  <tr>
    <th>Name</th>
    <th>Mobile</th>
    <th>Address</th>
    <th>Userid</th>
	<th>Role</th>
    <th>Password</th>
    <th>Location</th>
	<th>Retailer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shoppers.each do |shopper| %>
  <tr>
    <td><%= shopper.name %></td>
    <td><%= shopper.mobile %></td>
    <td><%= shopper.address %></td>
    <td><%= shopper.userid %></td>
	<td><%= shopper.role %></td>
    <td><%= shopper.password %></td>
    <td><%= shopper.location %></td>
	<td><%= shopper.retailer_id %></td>
    <td><%= link_to 'Show', shopper %></td>
    <td><%= link_to 'Edit', edit_shopper_path(shopper) %></td>
	<!-- <td><%= link_to 'Copy', copy_shopper_path(shopper) %></td> -->

  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shopper', new_shopper_path %>

app/views/shoppers/login.html.erb
<h1>Shopper login</h1>
<script>
localStorage.clear();
</script>

<%= render 'loginform' %>

<%= link_to 'Register New Shopper', new_shopper_path %>

app/views/shoppers/login_check_ajax.html.erb
{"formAuthenticityToken":"<%= form_authenticity_token %>"}

app/views/shoppers/new.html.erb
<h1>New shopper</h1>

<%= render 'form' %>

<%= link_to 'Go Back', login_shoppers_path %>

app/views/shoppers/orders.html.erb
<div data-role="page" id="order_page">
  <script>
	jQuery('#order_page').live('pageinit',function(event){
	  retailer_order();
	});
  </script>

  <div data-theme="b" data-role="header">
	<h3>
	  jiffeez <%=@shopper.name%>
	</h3>
	<a data-role="button" data-transition="reverse" data-rel="back" data-theme="e" data-add-back-btn="true" data-icon="arrow-l" data-iconpos="left">
	  Back
	</a>
	<a data-role="button" data-direction="reverse" data-transition="slide" data-theme="e" href="#categpage" onclick="shopping_categpage()" data-icon="home" data-iconpos="notext">
	</a>
  </div>
  <div data-role="content" class="white">
	<div>
	  <ul data-role="listview" id="in-process" > </ul>
	</div>
  </div>
</div>

<div data-role="page" id="shoppingcart_page">
  <script>
	jQuery('#shoppingcart_page').live('pageinit',function(event){
	  shoppingcart_display();
	});
	function changePage(){
	  jQuery(document).trigger('simpledialog', {'method':'close'});
	  if(globalCatId == null)
		$.mobile.changePage("#categpage");
	  else
		funcsub(globalCatId);
	}
  </script>
  <div data-theme="b" data-role="header">
	<h3>
	  Order Details
	</h3>
  </div>
  <div data-role="content" class="white">
	<div id="purchaseditemlistdiv">
	</div>
  </div>
</div>

app/views/shoppers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @shopper.name %>
</p>

<p>
  <b>Mobile:</b>
  <%= @shopper.mobile %>
</p>

<p>
  <b>Address:</b>
  <%= @shopper.address %>
</p>

<p>
  <b>Userid:</b>
  <%= @shopper.userid %>
</p>

<p>
  <b>Password:</b>
  <%= @shopper.password %>
</p>

<p>
  <b>Location:</b>
  <%= @shopper.location %>
</p>

<p>
  <b>Role:</b>
  <%= @shopper.role %>
</p>

<p>
  <b>Retailer:</b>
  <%= ((@retailer = Retailer.find_by_id(@shopper.retailer_id)) == nil)? "None": "#{@retailer.id} - #{@retailer.name}" %>
</p>


<%= link_to 'Edit', edit_shopper_path(@shopper) %> |
<%= link_to 'Back', shoppers_path %>