config/routes.rb
Schema::Application.routes.draw do
	match "login" => "shoppers#login", :as => :login
	match "out" => "shoppers#logout", :as => :out
	match "m" => "products#choose#categpage", :as => :m
	
  resources :retailers do
  	member do
  		get 'orders'
  	end
  	collection do
  		get 'delivery_times'
      post 'order_sent'
      post 'order_delivered'
      post 'undo_order_delivery'
  	end
  end

  resources :shoppers do
		member do
			get 'orders'
			get 'copy'
			post 'login_check_ajax'
			
		end
		collection do
				post 'register'
				get 'mobile_register'
				get 'mobile_verify'
				get 'mobile_remind_password'
				get 'getorders'
				get 'login'
				post 'login_check'
				post 'login_check_ajax'
				get 'logout'
    end
	end
  resources :items do
		collection do
				get 'select'
				get 'remove'
				get 'checkcart'
				get 'favorites'
        end
	end
  resources :shoppingcarts do
		collection do
				get 'checkout'
				get 'placeorder'
				get 'getorders'
				post 'processOrder'
				get 'get_cart_details'
    end
	end

  resources :brands

  resources :subcategs

  resources :categs 

  resources :products do
  collection do
				get 'choose'			
        end
	end
	
	resources :admin do
	collection do
		get 'compute_subcategbrand_promotions'
		get 'autocompute_product_promotions'
	end
	end
	
	resources :my_lists do
  collection do
				get 'create_my_list'
				get 'all_my_lists'
				get 'get_by_id'
        end
	end

end

app/models/subcateg.rb
class Subcateg < ActiveRecord::Base
	
	def compute_promotion
		
		@promoted_subcategs = Product.where(:subcid => self.subcid, :is_promotion => 1)
		if (@promoted_subcategs.empty?) 
			self.is_promotion = 0 
		else 
			self.is_promotion = 1
		end
	end
	#added by mandar
	def self.compute_promotions
	
		@subcategs = Subcateg.all
		
		@subcategs.each do |sc|
			sc.compute_promotion
			sc.save
		end
		
	end
end

app/controllers/subcategs_controller.rb
class SubcategsController < ApplicationController
	layout "choose_onepg"
  # GET /subcategs
  # GET /subcategs.json
  def index
    @subcategs = Subcateg.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json=> @subcategs }
    end
  end

  # GET /subcategs/1
  # GET /subcategs/1.json
  def show
    @subcateg = Subcateg.find_by_id(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json=> @subcateg }
    end
  end

  # GET /subcategs/new
  # GET /subcategs/new.json
  def new
    @subcateg = Subcateg.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json=> @subcateg }
    end
  end

  # GET /subcategs/1/edit
  def edit
    @subcateg = Subcateg.find_by_id(params[:id])
  end

  # POST /subcategs
  # POST /subcategs.json
  def create
    @subcateg = Subcateg.new(params[:subcateg])

    respond_to do |format|
      if @subcateg.save
        format.html { redirect_to @subcateg, :notice=> 'Subcateg was successfully created.' }
        format.json { render :json=> @subcateg, :status=> :created, :location=> @subcateg }
      else
        format.html { render :action=> "new" }
        format.json { render :json=> @subcateg.errors, :status=> :unprocessable_entity }
      end
    end
  end

  # PUT /subcategs/1
  # PUT /subcategs/1.json
  def update
    @subcateg = Subcateg.find_by_id(params[:id])

    respond_to do |format|
      if @subcateg.update_attributes(params[:subcateg])
        format.html { redirect_to @subcateg, :notice=> 'Subcateg was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action=> "edit" }
        format.json { render :json=> @subcateg.errors, :status=> :unprocessable_entity }
      end
    end
  end

  # DELETE /subcategs/1
  # DELETE /subcategs/1.json
  def destroy
    @subcateg = Subcateg.find_by_id(params[:id])
    @subcateg.destroy

    respond_to do |format|
      format.html { redirect_to subcategs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/subcategs_helper.rb
module SubcategsHelper
end

app/views/subcategs/_form.html.erb
<%= form_for(@subcateg) do |f| %>
  <% if @subcateg.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subcateg.errors.count, "error") %> prohibited this subcateg from being saved:</h2>

      <ul>
      <% @subcateg.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subcid %><br />
    <%= f.number_field :subcid %>
  </div>
  <div class="field">
    <%= f.label :cid %><br />
    <%= f.number_field :cid %>
  </div>
  <div class="field">
    <%= f.label :subcategname %><br />
    <%= f.text_field :subcategname %>
  </div>
  <div class="field">
    <%= f.label :order %><br />
    <%= f.text_field :order %>
  </div>
  <div class="field">
    <%= f.label :Subcateg %><br />
    <%= f.text_field :Subcateg %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subcategs/edit.html.erb
<h1>Editing subcateg</h1>

<%= render 'form' %>

<%= link_to 'Show', @subcateg %> |
<%= link_to 'Back', subcategs_path %>

app/views/subcategs/index.html.erb
<h1>Listing subcategs</h1>

<table>
  <tr>
    <th>Subcid</th>
    <th>Cid</th>
    <th>Subcategname</th>
    <th>Order</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subcategs.each do |subcateg| %>
  <tr>
    <td><%= subcateg.subcid %></td>
    <td><%= subcateg.cid %></td>
    <td><%= subcateg.subcategname %></td>
    <td><%= subcateg.order %></td>
    <td><%= link_to 'Show', subcateg %></td>
    <td><%= link_to 'Edit', edit_subcateg_path(subcateg) %></td>
    <td><%= link_to 'Destroy', subcateg, :confirm=> 'Are you sure?', :method=> :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subcateg', new_subcateg_path %>

app/views/subcategs/new.html.erb
<h1>New subcateg</h1>

<%= render 'form' %>

<%= link_to 'Back', subcategs_path %>

app/views/subcategs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Subcid:</b>
  <%= @subcateg.subcid %>
</p>

<p>
  <b>Cid:</b>
  <%= @subcateg.cid %>
</p>

<p>
  <b>Subcategname:</b>
  <%= @subcateg.subcategname %>
</p>

<p>
  <b>Order:</b>
  <%= @subcateg.order %>
</p>

<p>
  <b>Product:</b>
  <%= @subcateg.Product %>
</p>

<p>
  <b>Subcateg:</b>
  <%= @subcateg.Subcateg %>
</p>


<%= link_to 'Edit', edit_subcateg_path(@subcateg) %> |
<%= link_to 'Back', subcategs_path %>