config/routes.rb
Schema::Application.routes.draw do
	match "login" => "shoppers#login", :as => :login
	match "out" => "shoppers#logout", :as => :out
	match "m" => "products#choose#categpage", :as => :m
	
  resources :retailers do
  	member do
  		get 'orders'
  	end
  	collection do
  		get 'delivery_times'
      post 'order_sent'
      post 'order_delivered'
      post 'undo_order_delivery'
  	end
  end

  resources :shoppers do
		member do
			get 'orders'
			get 'copy'
			post 'login_check_ajax'
			
		end
		collection do
				post 'register'
				get 'mobile_register'
				get 'mobile_verify'
				get 'mobile_remind_password'
				get 'getorders'
				get 'login'
				post 'login_check'
				post 'login_check_ajax'
				get 'logout'
    end
	end
  resources :items do
		collection do
				get 'select'
				get 'remove'
				get 'checkcart'
				get 'favorites'
        end
	end
  resources :shoppingcarts do
		collection do
				get 'checkout'
				get 'placeorder'
				get 'getorders'
				post 'processOrder'
				get 'get_cart_details'
    end
	end

  resources :brands

  resources :subcategs

  resources :categs 

  resources :products do
  collection do
				get 'choose'			
        end
	end
	
	resources :admin do
	collection do
		get 'compute_subcategbrand_promotions'
		get 'autocompute_product_promotions'
	end
	end
	
	resources :my_lists do
  collection do
				get 'create_my_list'
				get 'all_my_lists'
				get 'get_by_id'
        end
	end

end

app/models/brand.rb
class Brand < ActiveRecord::Base
	
	def self.compute_promotions
	
		@brands = Brand.all
		#Brand.update_all({:is_promotion => '0'})
		
		@brands.each do |brand|
#added by mandar			
			@promoted_brand_products = Product.where(:brandid => brand.id, :is_promotion => 1)
			
			if (@promoted_brand_products.empty?) 
				brand.is_promotion = 0
			else 
				brand.is_promotion = 1
			end
			
			brand.save
			
		end
		
	end

end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
	layout "choose_onepg"
  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json=> @brands }
    end
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
    @brand = Brand.find_by_id(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json=> @brand }
    end
  end

  # GET /brands/new
  # GET /brands/new.json
  def new
    @brand = Brand.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json=> @brand }
    end
  end

  # GET /brands/1/edit
  def edit
    @brand = Brand.find_by_id(params[:id])
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(params[:brand])

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, :notice=> 'Brand was successfully created.' }
        format.json { render :json=> @brand, :status=> :created, :location=> @brand }
      else
        format.html { render :action=> "new" }
        format.json { render :json=> @brand.errors, :status=> :unprocessable_entity }
      end
    end
  end

  # PUT /brands/1
  # PUT /brands/1.json
  def update
    @brand = Brand.find_by_id(params[:id])

    respond_to do |format|
      if @brand.update_attributes(params[:brand])
        format.html { redirect_to @brand, :notice=> 'Brand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action=> "edit" }
        format.json { render :json=> @brand.errors, :status=> :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand = Brand.find_by_id(params[:id])
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to brands_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.erb
<%= form_for(@brand) do |f| %>
  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% @brand.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brandid %><br />
    <%= f.number_field :brandid %>
  </div>
  <div class="field">
    <%= f.label :subcid %><br />
    <%= f.number_field :subcategid %>
  </div>
  <div class="field">
    <%= f.label :cid %><br />
    <%= f.number_field :cid %>
  </div>
  <div class="field">
    <%= f.label :brandname %><br />
    <%= f.text_field :brandname %>
  </div>
  <div class="field">
    <%= f.label :order %><br />
    <%= f.text_field :order %>
  </div>
  <div class="field">
    <%= f.label :Brand %><br />
    <%= f.text_field :Brand %>
  </div>
  <div class="field">
    <%= f.label :Product %><br />
    <%= f.text_field :Product %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing brand</h1>

<%= render 'form' %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<h1>Listing brands</h1>

<table>
  <tr>
    <th>Brandid</th>
    <th>Subcategid</th>
    <th>Cid</th>
    <th>Brandname</th>
    <th>Order</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @brands.each do |brand| %>
  <tr>
    <td><%= brand.brandid %></td>
    <td><%= brand.subcategid %></td>
    <td><%= brand.cid %></td>
    <td><%= brand.brandname %></td>
    <td><%= brand.order %></td>
    <td><%= link_to 'Show', brand %></td>
    <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
    <td><%= link_to 'Destroy', brand, :confirm=> 'Are you sure?', :method=> :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Brand', new_brand_path %>

app/views/brands/new.html.erb
<h1>New brand</h1>

<%= render 'form' %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Brandid:</b>
  <%= @brand.brandid %>
</p>

<p>
  <b>Subcid:</b>
  <%= @brand.subcid %>
</p>

<p>
  <b>Cid:</b>
  <%= @brand.cid %>
</p>

<p>
  <b>Brandname:</b>
  <%= @brand.brandname %>
</p>

<p>
  <b>Order:</b>
  <%= @brand.order %>
</p>

<p>
  <b>Brand:</b>
  <%= @brand.Brand %>
</p>

<p>
  <b>Product:</b>
  <%= @brand.Product %>
</p>


<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>