config/routes.rb
Schema::Application.routes.draw do
	match "login" => "shoppers#login", :as => :login
	match "out" => "shoppers#logout", :as => :out
	match "m" => "products#choose#categpage", :as => :m
	
  resources :retailers do
  	member do
  		get 'orders'
  	end
  	collection do
  		get 'delivery_times'
      post 'order_sent'
      post 'order_delivered'
      post 'undo_order_delivery'
  	end
  end

  resources :shoppers do
		member do
			get 'orders'
			get 'copy'
			post 'login_check_ajax'
			
		end
		collection do
				post 'register'
				get 'mobile_register'
				get 'mobile_verify'
				get 'mobile_remind_password'
				get 'getorders'
				get 'login'
				post 'login_check'
				post 'login_check_ajax'
				get 'logout'
    end
	end
  resources :items do
		collection do
				get 'select'
				get 'remove'
				get 'checkcart'
				get 'favorites'
        end
	end
  resources :shoppingcarts do
		collection do
				get 'checkout'
				get 'placeorder'
				get 'getorders'
				post 'processOrder'
				get 'get_cart_details'
    end
	end

  resources :brands

  resources :subcategs

  resources :categs 

  resources :products do
  collection do
				get 'choose'			
        end
	end
	
	resources :admin do
	collection do
		get 'compute_subcategbrand_promotions'
		get 'autocompute_product_promotions'
	end
	end
	
	resources :my_lists do
  collection do
				get 'create_my_list'
				get 'all_my_lists'
				get 'get_by_id'
        end
	end

end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :Categ
	belongs_to :Subcateg
	belongs_to :Brand
	
	def self.lookup_anid(product_id)
		
		@product = Product.find(:first, :conditions => ["uom like ?", "%:#{product_id},%"])
		@anid = product_id

		if (!@product.nil?)
			@anid = @product.id
		end
		logger.debug("product anid: #{@anid} for input #{product_id}")

		return @anid
		
	end
	
	def auto_compute_promotion	
#added by mandar	
		@PromoDiscountLimit = 5.0
		@uom_string = self.uom.to_s
		@uom_string_check = self.valid_json?(@uom_string)
		if @uom_string_check
			@uom_json = JSON.parse(@uom_string)
			if @uom_json.count > 1
				@uom_json.each do |item|
					item["mrp"].to_f
					item["price"].to_f
					@discount_percent = ((item["mrp"].to_f - item["price"].to_f) * 100 / item["mrp"].to_f ) 
					is_promotional_item = (@discount_percent > @PromoDiscountLimit)? 1 : 0
					if is_promotional_item == 1
						self.is_promotion = 1
						break
					else
						self.is_promotion = 0
					end
				end
				self.save
			else
				calculate_promo_flag(self,@PromoDiscountLimit)
			end
		else
			calculate_promo_flag(self,@PromoDiscountLimit)
		end
	end
	
	def self.auto_compute_promotions
		@products = Product.all
		@products.each do |prod|
			prod.auto_compute_promotion
			prod.save
		end
#added by mandar
	end
	
	def valid_json? json_  
	  JSON.parse(json_)  
	  return true  
		rescue JSON::ParserError  
	  	return false  
	end

	def calculate_promo_flag(item,promo_discount_limit)
		discount_percent = ((item.mrp.to_f - item.sellprice.to_f) /item.mrp.to_f) * 100
		item.is_promotion = (discount_percent > promo_discount_limit)? 1 : 0
		item.save
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  layout "choose_onepg"
  # GET /products
  # GET /products.json
  def index
    
		@flag_promo = nil
		@flag_active = nil
		
		if (params[:promo] == 't')
			@flag_promo = true
		else 
			if (params[:promo] == 'f')
				@flag_promo = false
			end
		end

		if (params[:active] == 't')
			@flag_active = true
		else 
			if (params[:active] == 'f')
				@flag_active = false
			end
		end

		puts "flag promo #{@flag_promo}"
		
		if (@flag_promo != nil) 
			@Product_Cnd = Product.where("is_promotion=?", (@flag_promo? 1: 0))
		elsif (@flag_active != nil) 
			@Product_Cnd = Product.where("is_active=?", (@flag_active? 1: 0))
		else
				@Product_Cnd = Product.where("1=1")
		end
		
		@products = @Product_Cnd.paginate(:page => params[:page], :per_page => 20)
 #added by mandar 
   @update_time = Categ.order('updated_at desc').first.updated_at.to_i
	    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find_by_id(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find_by_id(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, :notice =>  'product was successfully created.' }
        format.json { render :json => @product, :status => :created, :location=> @product }
      else
        format.html { render :action =>  "new" }
        format.json { render :json => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find_by_id(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, :notice =>  'product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action =>  "edit" }
        format.json { render :json => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find_by_id(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
  def choose
		
		@page = 1			  # if page number isn't specified
		@per_page = 100	#	upper limit per page
		
		@flag_promo = nil

		if (params.has_key?("promo"))
			if (params[:promo] == 'true')
				@flag_promo = true
			else
				@flag_promo = false
			end
		end
		
		if (params.has_key?("page"))
			
			@page = params[:page]
			
			if (params.has_key?("per_page"))
				@per_page = params[:per_page]
			else
				@per_page = 6
			end

		end
		
		if (params.has_key?("page"))
			
			@page = params[:page]
			
			if (params.has_key?("per_page"))
				@per_page = params[:per_page]
			else
				@per_page = 6
			end
			
			logger.debug("Page number: #{params[:page]} - limiting per page: #{@per_page}")
			
		else
			logger.debug("No pagination - page 1, limit 100")
		end
			
		#@product = product
		#puts(params['cid'])
		if(params.has_key?("cid"))				#Can also use: if("cid" in params)
			@subcateg = Subcateg.paginate(:conditions => ["cid = ? ", params["cid"]], :order=>"subcid", 
				:page => @page, :per_page => @per_page );
		elsif(params.has_key?("subcid"))				#Can also use: if("subcid" in params)
			#if (@flag_promo.nil?)
			#	@Product_Cnd = Product.all
			#else
				@Product_Cnd = Product.where("is_active=?", (@flag_promo? 1: 0))
			#end
			@product = Product.paginate(:conditions => ["subcid = ?", params["subcid"]],:order=>"product,variant,size", 
				:page => @page, :per_page => @per_page );
		elsif(params.has_key?("subcategid"))				#Can also use: if("subcid" in params)
			@brand = Brand.paginate(:conditions => ["subcategid = ? ", params["subcategid"]],:order=>"6 desc", 
				:page => @page, :per_page => @per_page );
		elsif(params.has_key?("brandid"))				#Can also use: if("subcid" in params)
			@products = Product.paginate(:conditions => ["brandid = ? AND is_active=1 AND uom is not null", params["brandid"]], 
			#@products = Product.paginate(:conditions => ["brandid = ? AND uom is not null", params["brandid"]], 
				:order => "product,variant", :order => "rank desc, sellprice desc",
				:page => @page, :per_page => @per_page );
		else
			@categs = Categ.paginate(:order => "cid", 
				:page => @page, :per_page => @per_page );
		end
		
		#	puts ActiveSupport::JSON.encode(@brand);
    respond_to do |format|
			if params.has_key?(:cid)
				format.html # choose.html.erb
				format.json { render :json => @subcateg }
			elsif params.has_key?(:subcid)
				format.html # choose.html.erb
				format.json { render :json => @product }
			elsif params.has_key?(:subcategid)
				format.html # choose.html.erb
				format.json { render :json => @brand }
			elsif params.has_key?(:brandid)
				format.html # choose.html.erb
				format.json { render :json => @products }
			else
				format.html # choose.html.erb
				format.json { render :json => @categs }	 
			end
		end
  end
	
	

	
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :subcategory %><br />
    <%= f.text_field :subcategory %>
  </div>
  <div class="field">
    <%= f.label :subcid %><br />
    <%= f.text_field :subcid %>
  </div>
  <div class="field">
    <%= f.label :product %><br />
    <%= f.text_field :product %>
  </div>
  <div class="field">
    <%= f.label :brand %><br />
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :brandid %><br />
    <%= f.text_field :brandid %>
  </div>
  <div class="field">
    <%= f.label :variant %><br />
    <%= f.text_field :variant %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :mrp %><br />
    <%= f.text_field :mrp %>
  </div>
  <div class="field">
    <%= f.label :sellprice %><br />
    <%= f.text_field :sellprice %>
  </div>
  <div class="field">
    <%= f.label :uom %><br />
    <%= f.text_field :uom %>
  </div>
  <div class="field">
    <%= f.label :rank %><br />
    <%= f.text_field :rank %>
  </div>
  <div class="field">
    <%= f.label :is_active %><br />
    <%= f.check_box :is_active checked_value = "1", unchecked_value = "0" %>
  </div>
  <div class="field">
    <%= f.label :is_promotion %><br />
    <%= f.check_box :is_promotion checked_value = "1", unchecked_value = "0" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<script type="text/javascript">

$(function() {
  $(".chkIsActive").change(function() {
	window.location.href="/products?active=" + $(this).val();
  });
  
  $(".chkIsPromo").change(function() {
	window.location.href="/products?promo=" + $(this).val();
  });
});

</script>
<div data-role="page" id="page0">
		<div data-theme="a" data-role="header">
			<h1>Listing products</h1>
		</div>
	<div data-theme="a" data-role="content">

<table>
  <tr>
    <th>Category</th>
    <th>Subcategory (id) </th>
    <th>Brand</th>
	<th>Variant</th>
    <th>Size</th>
    <th>Mrp</th>
    <th>Sellprice</th>
	<th>Active</th>
	<th>Promo</th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.category %></td>
    <td><%= product.subcategory %> <%=product.subcid%></td>
    <td><%= product.brand %> <%=product.brandid%></td>
	<td><%= product.variant %></td>
    <td><%= product.size %></td>
    <td><%= product.mrp %></td>
    <td><%= product.sellprice %></td>
	<td><%= product.is_active %></td>
	<td><%= product.is_promotion %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, :confirm=> 'Are you sure?', :method=> :delete %></td>
  </tr>
<% end %>
</table>

	  <%= will_paginate @products %>
	  
<br />

<%= link_to 'New product', new_product_path %>&nbsp&nbsp<%= link_to 'Choose a category', choose_products_path %>

	</div>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Category:</b>
  <%= @product.category %>
</p>

<p>
  <b>Subcategory:</b>
  <%= @product.subcategory %>
</p>

<p>
  <b>Subcategory ID:</b>
  <%= @product.subcid%>
</p>
<p>
  <b>Product:</b>
  <%= @product.product %>
</p>

<p>
  <b>Brand:</b>
  <%= @product.brand %>
</p>
<p>
  <b>Brand ID:</b>
  <%= @product.brandid %>
</p>

<p>
  <b>Variant:</b>
  <%= @product.variant %>
</p>

<p>
  <b>Size:</b>
  <%= @product.size %>
</p>

<p>
  <b>Mrp:</b>
  <%= @product.mrp %>
</p>

<p>
  <b>Sellprice:</b>
  <%= @product.sellprice %>
</p>

<p>
  <b>Uom:</b>
  <%= @product.uom %>
</p>

<p>
  <b>Rank:</b>
  <%= @product.rank %>
</p>

<p>
  <b>Is Active:</b>
  <%= @product.is_active %>
</p>

<p>
  <b>Promotion:</b>
  <%= @product.is_promotion %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>